source :rubygems

gem "capybara"
gem "cucumber"
gem "phantomjs", :require => 'phantomjs/poltergeist'
gem "poltergeist"
gem "rubyzip"
gem "selenium-cucumber"
gem "selenium-webdriver"
gem "webdrivers", "~> 3.0"
gem 'rspec-expectations'
